import type { ConsoleDataProvider } from "./adapters";
import {
  assistantActions,
  configs,
  customers,
  holdings,
  metrics,
  opportunities,
  orders,
  metricDefinitions,
  agentTasks,
  agentAuditLogs,
  agentGovernanceRules,
  apiIntegrationModules,
  integrationChecklist,
  performanceStrategies,
  opportunityAttributions,
  reportTemplates,
  reportGenerationRecords,
  scheduledReportTasks,
  risks,
  tasks,
} from "./mockData";

export const mockProvider: ConsoleDataProvider = {
  getMetrics: () => metrics,
  getCustomers: () => customers,
  getOrders: () => orders,
  getHoldings: () => holdings,
  getRiskEvents: () => risks,
  getOpportunities: () => opportunities,
  getConfigItems: () => configs,
  getTasks: () => tasks,
  getAssistantActions: () => assistantActions,
  getReportTemplates: () => reportTemplates,
  getReportGenerationRecords: () => reportGenerationRecords,
  getScheduledReportTasks: () => scheduledReportTasks,
  getMetricDefinitions: () => metricDefinitions,
  getOpportunityAttributions: () => opportunityAttributions,
  getAgentTasks: () => agentTasks,
  getAgentGovernanceRules: () => agentGovernanceRules,
  getAgentAuditLogs: () => agentAuditLogs,
  getApiIntegrationModules: () => apiIntegrationModules,
  getIntegrationChecklist: () => integrationChecklist,
  getPerformanceStrategies: () => performanceStrategies,
};
